name: "Terraform Valida Modulo"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  terraform:
      uses: "mentoriaiac/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@v1"
      with: 
        tf_version: "1.0.0"
        os_version: "ubuntu-20.04"
      secrets:
        token: ${{ secrets.TOKEN }}
